//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public int Admin_ID { get; set; }
        public int User_ID { get; set; }
        public string AdminName { get; set; }
        public string SurName { get; set; }
        public string PhoneNum { get; set; }
    
        public virtual User User { get; set; }
    }
}
