//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DateOrTimeSlotOrDriver
    {
        public int Employee_ID { get; set; }
        public int DateorTimeslotDirive_ID { get; set; }
        public int DateorTimeslot_ID { get; set; }
        public string Description { get; set; }
        public int BookingInstance_ID { get; set; }
    
        public virtual BookingInstance BookingInstance { get; set; }
        public virtual DateOrTimeSlot DateOrTimeSlot { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
