//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuotationLine
    {
        public int QuotationLine_ID { get; set; }
        public int QuotationRequest_ID { get; set; }
        public string QuotationLineDescription { get; set; }
        public int Quotation_ID { get; set; }
        public int Service_ID { get; set; }
    
        public virtual Quotation Quotation { get; set; }
        public virtual QuotationRequest QuotationRequest { get; set; }
        public virtual Service Service { get; set; }
    }
}
