//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nazox.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Administrator
    {
        public int Admin_ID { get; set; }
        public string AdminName { get; set; }
        public Nullable<int> User_ID { get; set; }
        public string SurName { get; set; }
        public string PhoneNum { get; set; }
        public string EmailAddress { get; set; }
    
        public virtual Administrator Administrator1 { get; set; }
        public virtual Administrator Administrator2 { get; set; }
        public virtual User User { get; set; }
    }
}
