//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nazox.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DateOrTimeSlotOrDriver
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DateOrTimeSlotOrDriver()
        {
            this.BookingInstances = new HashSet<BookingInstance>();
        }
    
        public int Employee_ID { get; set; }
        public int DateorTimeslotDiriver_ID { get; set; }
        public int Timeslot_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookingInstance> BookingInstances { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual TimeSlot TimeSlot { get; set; }
    }
}
