//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nazox.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EasyMovingSystemEntities : DbContext
    {
        public EasyMovingSystemEntities()
            : base("name=EasyMovingSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Administrator> Administrators { get; set; }
        public virtual DbSet<Application> Applications { get; set; }
        public virtual DbSet<ApplicationStatu> ApplicationStatus { get; set; }
        public virtual DbSet<BackgroundCheckStatu> BackgroundCheckStatus { get; set; }
        public virtual DbSet<Booking> Bookings { get; set; }
        public virtual DbSet<BookingInstance> BookingInstances { get; set; }
        public virtual DbSet<BookingStatu> BookingStatus { get; set; }
        public virtual DbSet<Candidate> Candidates { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<DateOrTimeSlotOrDriver> DateOrTimeSlotOrDrivers { get; set; }
        public virtual DbSet<DocumentFile> DocumentFiles { get; set; }
        public virtual DbSet<DocumentType> DocumentTypes { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<EmployeeStatu> EmployeeStatus { get; set; }
        public virtual DbSet<EmployeeType> EmployeeTypes { get; set; }
        public virtual DbSet<FeedbackType> FeedbackTypes { get; set; }
        public virtual DbSet<Inspection> Inspections { get; set; }
        public virtual DbSet<InspectionItem> InspectionItems { get; set; }
        public virtual DbSet<InspectionType> InspectionTypes { get; set; }
        public virtual DbSet<JobListing> JobListings { get; set; }
        public virtual DbSet<JobType> JobTypes { get; set; }
        public virtual DbSet<License> Licenses { get; set; }
        public virtual DbSet<ListingStatu> ListingStatus { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<NotificationType> NotificationTypes { get; set; }
        public virtual DbSet<Password> Passwords { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<PaymentStatu> PaymentStatus { get; set; }
        public virtual DbSet<PaymentType> PaymentTypes { get; set; }
        public virtual DbSet<Quotation> Quotations { get; set; }
        public virtual DbSet<QuotationLine> QuotationLines { get; set; }
        public virtual DbSet<QuotationRequest> QuotationRequests { get; set; }
        public virtual DbSet<QuotationRequestLine> QuotationRequestLines { get; set; }
        public virtual DbSet<RentalStatu> RentalStatus { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<RoleType> RoleTypes { get; set; }
        public virtual DbSet<Service> Services { get; set; }
        public virtual DbSet<TblFeedback> TblFeedbacks { get; set; }
        public virtual DbSet<TimeSlot> TimeSlots { get; set; }
        public virtual DbSet<Title> Titles { get; set; }
        public virtual DbSet<TrackingStatu> TrackingStatus { get; set; }
        public virtual DbSet<Truck> Trucks { get; set; }
        public virtual DbSet<TruckPhoto> TruckPhotoes { get; set; }
        public virtual DbSet<TruckStatu> TruckStatus { get; set; }
        public virtual DbSet<TruckType> TruckTypes { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserNotification> UserNotifications { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<RentalAgreement> RentalAgreements { get; set; }
    }
}
