//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nazox.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblFeedback
    {
        public int Feedback_ID { get; set; }
        public int FeedbackType_ID { get; set; }
        public string FeedbackDescription { get; set; }
        public int Service_ID { get; set; }
        public int Client_ID { get; set; }
        public Nullable<int> Booking_ID { get; set; }
        public int Rating { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual FeedbackType FeedbackType { get; set; }
        public virtual Service Service { get; set; }
    }
}
