//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nazox.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TruckPhoto
    {
        public int Photo_ID { get; set; }
        public byte[] Photo { get; set; }
        public int Truck_ID { get; set; }
    
        public virtual Truck Truck { get; set; }
    }
}
