//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nazox.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRole
    {
        public int Role_ID { get; set; }
        public Nullable<int> User_ID { get; set; }
        public Nullable<int> RoleTypeId { get; set; }
        public Nullable<int> Admin_ID { get; set; }
    
        public virtual RoleType RoleType { get; set; }
        public virtual User User { get; set; }
    }
}
